version: "3.8"
services:
  database:
    image: postgres
    container_name: myfut
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myfut
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
